/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


// this part of work is done by ID : 13.01.04.033

package book_share_lend;


import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.*;
/**
 *
 * @author bdtech
 */
public class User2_lend extends javax.swing.JFrame {

    /**
     * Creates new form user2
     */
    
    
    // for database connection
       static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String DB_URL = "jdbc:mysql://localhost/netprodb";

   //  Database credentials
   static final String USER = "root";
   static final String PASS = "";
    
    
     static Connection con;
    static Statement st;
    static ResultSet rs;
    
    
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    static int flag=0;
    
    String[] book;
    String[] temp;
    
    //new
    
     static String msgin="";
            
       static     String msgin2="";
    
    //new
    
    public User2_lend() {
        initComponents();
        
        setResizable(false);
      setTitle("User 2 Lend book"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        accept_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        msg_area2 = new javax.swing.JTextArea();
        reject_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        accept_button.setText("accept");
        accept_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_buttonActionPerformed(evt);
            }
        });

        msg_area2.setColumns(20);
        msg_area2.setRows(5);
        jScrollPane2.setViewportView(msg_area2);

        reject_button.setText("reject");
        reject_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reject_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("User id");

        jLabel2.setText("Book Name");

        jLabel3.setText("Do you wnat to share?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accept_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reject_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(136, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accept_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reject_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accept_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_buttonActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
        
          try
        {
            
            flag=1;
            String msgout="";
         
           msgout="accepted";
           //msgout=msg_text.getText().trim();
           dout.writeUTF(msgout);  // for sending accepted msg
           
           
           
           
           //sending file start
            if(msgin.trim().equals("User1"))
            {
                            ServerSocket serverSocket = new ServerSocket(15123); 
                Socket socket = serverSocket.accept();
                
                
                // for sending the book file to User1
                System.out.println("Accepted connection : " + socket);
                File transferFile = new File ("G:\\User2\\"+msgin2+".pdf"); 
                byte [] bytearray = new byte [(int)transferFile.length()];
                FileInputStream fin = new FileInputStream(transferFile);
                BufferedInputStream bin = new BufferedInputStream(fin);
                bin.read(bytearray,0,bytearray.length); 
                OutputStream os = socket.getOutputStream();
                System.out.println("Sending Files...");
                os.write(bytearray,0,bytearray.length);
                os.flush(); socket.close(); 
                System.out.println("File transfer complete");
            }
           
           //sending file end
           
           
           
           
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_accept_buttonActionPerformed

    private void reject_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reject_buttonActionPerformed
        // TODO add your handling code here:
        
        flag=0;
        
        
          try
        {
           String msgout="rejected";
           //msgout=msg_text.getText().trim();
           dout.writeUTF(msgout);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_reject_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User2_lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User2_lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User2_lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User2_lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User2_lend().setVisible(true);
            }
        });
        
        
        
        Connection conn = null;
   Statement stmt = null;
        
        
        
        
        try
        {
            s=new Socket("127.0.0.1",1201);// for setting the ip address & port number
            din=new DataInputStream(s.getInputStream());
            dout=new DataOutputStream(s.getOutputStream());
           
            
            int i;
            
            
           
            
            while(!msgin.equals("exit"))
            {
                msgin=din.readUTF(); // get the user id
                
                msg_area.setText(msg_area.getText().trim()+"\n"+msgin);
                
                
                msgin2=din.readUTF(); // get the book name
                
                
                //try
                
      
        
        
        
        
        
   
        
        
        
        
                //try
                
                
               
                
                msg_area2.setText(msg_area2.getText().trim()+"\n"+msgin2);
                //flag=1;
                
                
                
                
                
     
                
                
                
            }
            
        }
        catch(Exception e)
        {
            
        }
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea msg_area;
    private static javax.swing.JTextArea msg_area2;
    private javax.swing.JButton reject_button;
    // End of variables declaration//GEN-END:variables
}
